version: 0.0 # CodeDeploy 버전 프로젝트 버전이 아니므로 0.0만 사용해야한다
os: linux
files:
  - source: / # CodeDeploy에서 전달해준 파일 중 destination으로 이동시킬 대상 지정 '/' = 전체 파일
    destination: /home/ec2-user/app/step2/zip/ # source에서 지정된 파일을 받을 위치 destination의 파일을로 jar파일 실행한다
    overwrite: yes # 기존에 있는 파일들이 있으면 덮어쓸지.

permissions: # CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# CodeDeploy 배포 단계에서 실행할 명령어를 지정
# ApplicationStart라는 단계에서 deploy.sh를 ec2-user권한으로 실행
# timeout: 60으로 스크립트 실행 60초 이상 수행되면 실패. 무한정 기다릴 수도 있으니
hooks:
  ApplicationStart:
    - chmod -x deploy.sh
    - location: deploy.sh
      timeout: 60
      runas: ec2-user
